version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn test:unit

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git