version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: yarn test:unit

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test